### ISSUE TITLE
How can i get register and get callback once file is played.

### ISSUE THREAD

**Issue by alphaDroid89** [jeancsanchez/JCPlayer#1]
Hi @jeancsanchez ,

Thanks for the sharing, how can i get the call back of each audio is played. I tried the sample application unfortunately i can't able get completion listener or info listener like a behavior. Can you please share us to add. Thanks.

**Comment by jeancsanchez** [comment]
You can just implement the interface JCPlayerServiceListener and you will have all callbacks needed.

**Comment by alphaDroid89** [comment]
@jeancsanchez  thanks 👍
