### ISSUE TITLE
How to kill JcPlayer ?

### ISSUE THREAD

**Issue by SimpleappRed** [jeancsanchez/JCPlayer#101]
How to kill the player from another activity /  fragment?
Thanks

**Comment by jeancsanchez** [comment]
You can get the JcPlayerManager singleton and kill the notification:

```Java
// In Java
JcPlayerManager.getInstance(this, null, null).get().kill();
```
```Kotlin
// In Kotlin
JcPlayerManager.getInstance(context).get()?.kill()
```

**Comment by SimpleappRed** [comment]
> You can get the JcPlayerManager singleton and kill the notification:
> 
> ```java
> // In Java
> JcPlayerManager.getInstance(this, null, null).get().kill();
> ```
> 
> ```kotlin
> // In Kotlin
> JcPlayerManager.getInstance(context).get()?.kill()
> ```

Thank you!
