### ISSUE TITLE
Android System kills the app when user minimize the app for long

### ISSUE THREAD

**Issue by EjilolaHammedEjitomiwa** [jeancsanchez/JCPlayer#107]
I use this library to develop on media player app, it works fine but when the user minimize the app for long the Android system silently kills the app.
I hope this bug get fixed.

**Thanks**

**Comment by jeancsanchez** [comment]
Hello @EjilolaHammedEjitomiwa.
I suspect this is a normal behavior from Android S.O. Generally, when your device RAM is small and the S.O needs more space to run Android kills apps. You can read more about it here: https://developer.android.com/guide/components/activities/process-lifecycle

I'm closing this issue for now... if you have more supplies and context for this problem, you can reopen it.
