### ISSUE TITLE
I want to disable/enable buttons according to my scenario? 

### ISSUE THREAD

**Issue by emretekin** [jeancsanchez/JCPlayer#109]
I want to disable/enable buttons according to my scenario?  
But I can't see and disable / enable feature. 

I know it's an enhancement task, If it has it, would be better.

**Comment by jeancsanchez** [comment]
@emretekin  I don't remember because have a long time I don't put my hands on code, but I think you can get the view reference and disable/enable or show/hide it manually. If you're using Kotlin you can get it by the `kts` or the traditional method  `findViewById`.
