### ISSUE TITLE
How to play the audio files on ListView Item Clicked?

### ISSUE THREAD

**Issue by lauyatkin** [jeancsanchez/JCPlayer#110]
I have finished creating a player control on the bottom of my screen.
However, any codes can retrieve the list of song and display on the screen - a ListView?
Moreover, how can perform a "Play Music" action when user taps the name of the song on the ListView item?
 
**Screenshots**
Just like that on the screenshots
![image](https://user-images.githubusercontent.com/50213891/102040660-66c85e80-3e08-11eb-9c9e-d4960d8a5ba8.png)

**Comment by LunevNF** [comment]
How?

**Comment by lauyatkin** [comment]
I find the code on this GitHub. It is out of the tutorial. You can just copy the code from it.

**Comment by LunevNF** [comment]
Thanks. I can play programmatically via JcPlayerManager
