### ISSUE TITLE
Reopen music plyer seekbar and title not working

### ISSUE THREAD

**Issue by rajjani88** [jeancsanchez/JCPlayer#111]
**Describe the bug**
I implemented this library. This is amazing. I got one small problem i need it to play in background so i create notification on view play button. when i close and reopen app. Player is working but seek bar and  song title is not

![device-2020-12-30-123539](https://user-images.githubusercontent.com/43672284/103338302-f2e2b300-4aa3-11eb-8271-7feb282bce25.png)

**Comment by jeancsanchez** [comment]
Hey @rajjani88 Thanks for your contribution. 
Can you share more info about your context, like `sdkCompile`, `device android version` , `what kind of file are these songs `, etc?

**Comment by rajjani88** [comment]
hi, 
Songs type : both raw file and url (mp3)
sdk compile :  30
device android version : 10 Samsung A50s 

Player is working fine. I need to play songs in background. When user reopen application by notification click or app icon click player is playing song and timer works you can see in this picture but seek bar won't response (updates / user input) and no song title is showing for current song.

I am sure that i did something wrong. because when we check isPlaying it returns true.

**Comment by rajjani88** [comment]
also i need help to move song to selected seekbar position

**Comment by jeancsanchez** [comment]
I have to investigate it... I suspect there is something wrong with the JcPlayerService with the new Android versions...

**Comment by rajjani88** [comment]
ok No problem. comment back if you find issues and solutions. Your are great Thanks. only this one issues and my project is done.

**Comment by jeancsanchez** [comment]
I'm closing it.  I've been testing and probably fixed in version `1.7.0` . If it happens again, reopen this issue and attach some video for me, please.

**Comment by jeancsanchez** [comment]
Yes, it continued happening, but it was fixed on version `2.7.1`
