### ISSUE TITLE
JcPlayer not working in android version 9, 10 and up

### ISSUE THREAD

**Issue by ibrelm** [jeancsanchez/JCPlayer#112]
JcPlayer steal loading in android 9,10 and up why this problem please fix this

**Comment by jeancsanchez** [comment]
Hello @ibrelm, thanks for you reporting.
I haven't been updating this library. This is my fault, I'll revisit this library and fix some problems for the new Android versions.
However, basically only I'm supporting this library and it's an open source project. So you, as a community member, can also send pull requests or forking it to fix these issues...

**Comment by jeancsanchez** [comment]
Probably fixed in version `1.7.0`

**Comment by ibrelm** [comment]
thanks
