### ISSUE TITLE
JcPlayerView icons are large 

### ISSUE THREAD

**Issue by pankajjangid** [jeancsanchez/JCPlayer#118]
I am using the SVG icon in my project and you can see that icons like next ,previous ,play and pause icons are large.
I set the size in SVG too but nothing change in view.

**Screenshot**

![Screenshot_6](https://user-images.githubusercontent.com/16424754/118950256-a5de7b00-b977-11eb-9833-76019e4758ba.png)

**XML Code**
```
<com.example.jean.jcplayer.view.JcPlayerView
                    android:id="@+id/jcplayer"
                    android:layout_width="match_parent"

                    android:layout_height="wrap_content"
                    android:gravity="bottom"
                    app:next_icon="@drawable/ic_forward"

                    app:next_icon_color="@android:color/white"
                    app:pause_icon_color="@android:color/white"
                    app:play_icon_color="@android:color/white"
                    app:previous_icon="@drawable/ic_backward"
                    app:previous_icon_color="@android:color/white"
                    app:progress_color="@android:color/white"
                    app:play_icon="@drawable/ic_play"
                    app:pause_icon="@drawable/ic_pause"
                    app:random_icon_color="@android:color/white"
                    app:repeat_icon_color="@android:color/white"
                    app:seek_bar_color="@android:color/white"
                    app:show_repeat_button="false"
                    app:show_random_button="false"

                    app:text_audio_current_duration_color="@android:color/white"
                    app:text_audio_duration_color="@android:color/white"
                    app:text_audio_title_color="@android:color/white" />

```

**Comment by jeancsanchez** [comment]
Hello, it's very strange. 
There are several ways to fix that, but one I remember now is to get the `jcplayerview` reference by id, and then get its child by id as well. With that you can set width and height programmatically.   Something like:

```kotlin
val playerView = findViewById(R.id.jcplayer)
playerView.findViewById(R.id.btnPlay).also { playButton ->
    // Set attrs here...
}
```

**Comment by pankajjangid** [comment]
I do this way but didn't happened, any other ways?


           `binding.jcplayer.findViewById<AppCompatImageButton>(R.id.btnPlay).also { playButton ->
                // Set attrs here...
                playButton.maxHeight = 24
                playButton.maxWidth = 24
            }
             
            binding.jcplayer.findViewById<AppCompatImageButton>(R.id.btnNext).also { playButton ->
                // Set attrs here...
                playButton.maxHeight = 24
                playButton.maxWidth = 24
            }


            binding.jcplayer.findViewById<AppCompatImageButton>(R.id.btnPrev).also { playButton ->
                // Set attrs here...
                playButton.maxHeight = 24
                playButton.maxWidth = 24
            }`

**Comment by jeancsanchez** [comment]
I don't think it's the right way to do that. 
Try resizing your buttons by layout params (https://stackoverflow.com/a/11294075/4916458)

**Comment by pankajjangid** [comment]
Thanks, @jeancsanchez , it's really helpful
