### ISSUE TITLE
How to get current time?

### ISSUE THREAD

**Issue by kaustubhk24** [jeancsanchez/JCPlayer#119]
**Describe the bug**
I want to get the current time

I am clicking the button and want to get current time of audio playing

**Comment by jeancsanchez** [comment]
Hello :)
Give a checkout in this issue #72

**Comment by kaustubhk24** [comment]
@jeancsanchez Still unclear, what you mean

**Comment by jeancsanchez** [comment]
@kaustubhk24
You should to implement https://github.com/jeancsanchez/JcPlayer/blob/master_v2/jcplayer/src/main/java/com/example/jean/jcplayer/JcPlayerManagerListener.kt 

With it, you'll be able to get current time by `onTimeChanged` method.
