### ISSUE TITLE
Slider and duration not synced to audio playing

### ISSUE THREAD

**Issue by H4zh4n** [jeancsanchez/JCPlayer#124]
_[Video attached at bottom for better explanation/visualization]_
A background on what I'm trying to achieve:
I have an app that has two distinct activities, a main window and (obviously) the second one that has the player.
The player is displayed in an AlertDialog, because I have two other different activities that require the same audio player.
so to avoid writing same code three times I came up with the solution of having a custom AlertDialog that has your beautiful library and opens through a menu click in all three.

When I open the second activity,
I can open the dialog, play the audio files (they are all mp3 files) with no issues.
I have managed to make it if the dialog is dismissed while playing and called (opened) again, it is synced perfectly. I achieved this by simply making sure to not reload the player again (not fetching the view again) if it's from the same Context as previous.

### **My Issue**
When the dialog is dismissed while the audio is playing, and I return to main activity, and back to second,
if I open the dialog, now the slider and the total/duration timer (AND play/pause button) is not synced, but current time of the audio is synced (the time the audio file is at). Slider is always at the end and total/duration time shows 00:00. I think mostly due to the fact that even if I open the same second activity I have to reload the player (do the findView ...) because although I opened the same second activity, the Context changed, and I HAVE to reload stuff or else the dialog won't show since I'm in a different context (still same activity but different context as previous one was destroyed).

I'm looking for way to refresh the slider and duration time of the audio file (AND the play/pause button accordingly) so it's synced as well when I reopen the dialog when revisiting the activity again and the audio is still playing.

Some other stuff that might be irrelevant or maybe useful for you to identify the issue :
* I only create/have one `JcPlayerManagerListener` and one `ArrayList<JcAudio>`  and initialize them once.
* I always run `initPlaylist()` on every dialog open again and do set the already created Manager and ArrayList to it everytime.
* For now, I only run `... new Dialog(context, style)` and `dialog.findViewById(R.id.audio_player)` when dialog is opened in a new context (meaning once every time user leaves and comes back).
* Most of my variables are set as static.

I believe overall if I only have the main activity and the other three loaded as fragments I could fix the issue by opening the dialog in main always (or even have it as a view in main like the sample app), but I was hoping there was a way to fix the issue currently without going through a major change in my app since all three are tied to a ton of other stuff just to fix that small UI bug.

_A demonstration of the issue :_  **_In some moments in the video you may see the timer/slider frozen, this is because I recorded a quick vid and when I edited it I slowed down the video so the on-vid text can be read, so no issues there. only the stuff not synced to player._**

https://user-images.githubusercontent.com/47919702/145464953-d7a66468-7453-418d-8217-8032df648f62.mp4

...

**Comment by jeancsanchez** [comment]
Hello @H4zh4n. Great explanation.

Do you have this sample code available for free? We need to debug the code to figure this out.

**Comment by H4zh4n** [comment]
@jeancsanchez this is a sample project with only the audio related stuff  :

[Sample for JCPlayer Issue](https://mega.nz/file/u0kVGATJ#HBjL3mxf_8OU0Cx0t0eriCZ21WuxeNeSao--D5ysfOM)

Apologies for the hassle and thanks a ton in advance.

**Comment by H4zh4n** [comment]
@jeancsanchez I'm terribly sorry, but is it possible that you look into it now maybe?

**Comment by jeancsanchez** [comment]
@H4zh4n Sorry for the delay.... can you post your code here on Github? I don't usually download zip files :)
But for now I have a suggestion for you: have you tried calling `jcplayer.kill()` when second activity is finished? I think if your player activity is finished, the player also has to be finished .

**Comment by H4zh4n** [comment]
@jeancsanchez 
sure thing, below link is for a repo I just made.
[JCPlayer Sample](https://github.com/H4zh4n/jcplayer-sample)

The thing is I don't want to kill the player. I want it to stay playing (it does, no issues there), the only issue I face is when I leave and go back into the second activity the stuff isn't synced to the audio which is still playing.

I was thinking maybe trying to kill it, play it again, and then (skip/seek) the audio might fix it, but I just couldn't find how to perform seekTo, I checked all other comments which you mentioned how through the `JcPlayerManager`, didn't work for me. can't call a method name seekTo or anything similar through anywhere.

Also, in the other issues I believe one person had the same issue as me [Issue#111](https://github.com/jeancsanchez/JcPlayer/issues/111)

**Comment by jeancsanchez** [comment]
Fixed on version `2.7.1`. 

Just call `player.resume()` method before showing your dialog. 
I created a [Pull Request](https://github.com/H4zh4n/jcplayer-sample/pull/1) for your repository  with the changes needed.

Thanks for feedaback ❤️

**Comment by H4zh4n** [comment]
@jeancsanchez 
Thank you so much for the great work. really appreciate it. everything works as intended now.
do you still prefer patreon as a method to support you ? I want to makeup a bit for the hassle I put you through.


I had another issue so below is only a heads-up for those that comes across this thread with same design structure as me.
hopefully it helps someone...
If ever wanted to stop the player and swap the audios with new files when the dialog is opened (say opening same dialog from different activity that has different audios to be played), it's best to place `jcplayer.kill()` before the the `findViewById` (best to put a null check there incase it's a first run).
I thought the `jcplayer.kill()` only stops the player, but from what I looked at I believe it clears everything related to the player, so it's _maybe_ required to init (do the `findViewById` again) after `jcplayer.kill()` in that situation.

your comment saying below helped me figure this out.
> have you tried calling `jcplayer.kill()` when second activity is finished? I think if your player activity is finished, the player also has to be finished.

**Comment by jeancsanchez** [comment]
One more note: it might be better to call `player.resume()` when your activity is in resumed state. To do that, your dialog need to Implements LifeCycleObserver interface.
