### ISSUE TITLE
 Android 12 API 31 : requires that one of FLAG

### ISSUE THREAD

**Issue by joyalalam** [jeancsanchez/JCPlayer#126]
required to avoid crash on Android 12 API 31 : requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

**Comment by josef130** [comment]
In order to fix this you can change :


```
.setContentIntent(PendingIntent.getActivity(context, NOTIFICATION_ID, openUi,
                    PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_CANCEL_CURRENT))
```

instead of :
.setContentIntent(PendingIntent.getActivity(context, NOTIFICATION_ID, openUi,
                    PendingIntent.FLAG_CANCEL_CURRENT))
                    
                    
                    
                    and

```
                            return PendingIntent.getBroadcast(context.applicationContext, id, playIntent,
            PendingIntent.FLAG_IMMUTABLE or PendingIntent.FLAG_UPDATE_CURRENT)
```

            
                instead of :    
                        return PendingIntent.getBroadcast(context.applicationContext, id, playIntent,
            PendingIntent.FLAG_UPDATE_CURRENT)
            
            
           Also you can contact me to fix it.

**Comment by jeancsanchez** [comment]
@josef130 this issue is duplicated and already have a solution. See #134. Thanks.
