### ISSUE TITLE
Query on target sdk 31 support 

### ISSUE THREAD

**Issue by W3-Anjan** [jeancsanchez/JCPlayer#133]
**Describe the bug**
When we are updating the compile & target SDK version to 31, the library is getting an error 

**To Reproduce**
1. Go to app/build.gradle
2. Change CompiledSDKVersion 31
3. Run Syncnow to build the project

**Comment by jeancsanchez** [comment]
@W3-Anjan 
I released a new version with the fix. Please use version 2.7.2.
