### ISSUE TITLE
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE 

### ISSUE THREAD

**Issue by mdkamal054** [jeancsanchez/JCPlayer#134]
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

**Comment by cjjbiz** [comment]
Having the same problem. anyone found a fix for this?

**Comment by sisnos** [comment]
Having the same problem !! please update the lib

**Comment by jeancsanchez** [comment]
@DecodeIndustry  @sisnos  @cjjbiz  
This  issue is duplicated with #133.
I released a new version with the fix. Please use version 1.7.2.
