### ISSUE TITLE
dependency not imported in java project

### ISSUE THREAD

**Issue by aivision369** [jeancsanchez/JCPlayer#139]
I have integrated this library in my JAVA project and its working fine. But right now when I sync project then unable to identify dependency and getting this `Could not find com.github.jeancsanchez:JcPlayer:2.7.2.` error.

I have added `maven { url 'https://jitpack.io' }` in project level build.gradel file and `implementation 'com.github.jeancsanchez:JcPlayer:2.7.2'` in app level build.gradle file.

I have checked library project code and its in Kotlin but unable to convert my current project from JAVA to Kotlin so Is it possible to add this player in my JAVA project?

**Comment by jeancsanchez** [comment]
Hi @IDFDeveloper,
What version is your Java?

**Comment by jeancsanchez** [comment]
For some reason, Jitpack repository did not create artifacts for the 2.7.2 version.
I just forced a rebuild and I think it is ok now.
Could you test it again?

**Comment by jeancsanchez** [comment]
Looks like it was resolved by issue #140. Closing this thread for now.
