### ISSUE TITLE
Failed to Reslove dependency ?

### ISSUE THREAD

**Issue by ziadkiwan** [jeancsanchez/JcPlayer#14]
Hello,

Thank you for the wonderful Project at least its not complicated as the others.. just the project i needed, 
i have a problem when i add the dependency to my android gradle it fails to resolve, thank you
i'm using:
compile 'io.github.jeancsanchez.jcplayer:jcplayer:2.0.3-alpha'

**Comment by jeancsanchez** [comment]
Hello friend :)

You need to add this on your project gradle:
```gradle
allprojects {
    repositories {
        jcenter()
        maven {
            url  "http://dl.bintray.com/jeancsanchez/maven"
        }
    }
}
```

**Comment by aarora-infy** [comment]
@jeancsanchez  Can you please update this in your readme as well?

**Comment by abhatnagar03** [comment]
@jeancsanchez  Can you please update this in your readme as well?

I am still not able to resolve the dependency, can you please help me out?

**Comment by jeancsanchez** [comment]
@abhatnagar03  @ziadkiwan 
 I recently released a new version of the library. Can you test it?
`com.github.jeancsanchez:JcPlayer:2.6.11` 
I am using the Jitpack now, see the readme for more info: 
https://github.com/jeancsanchez/JcPlayer/blob/master_v2/README.md

**Comment by abhatnagar03** [comment]
Failed to resolve: com.github.jeancsanchez:JcPlayer:2.6.11

**Comment by AbuNahed** [comment]
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.jeancsanchez:JcPlayer:{version}.
Show Details
Affected Modules: app

**Comment by jeancsanchez** [comment]
@AbuNahed Replace {version} with the library's version.

**Comment by dickyprtma** [comment]
i have same problem too i've replaced the {version} with latest version 2.6.16 but error appear unable to resolve dependency

**Comment by jeancsanchez** [comment]
@dzuerst I have tested and it's working like a charm. Please, read again the readme file to be sure you are following the correct steps.

**Comment by dickyprtma** [comment]
thanks it works, I misplaced the maven
buildscript {
    repositories {
        google()
        jcenter()
        maven ()
    }

here is the right location
allprojects {
    repositories {
        google()
        jcenter()
        maven ()
    }
}

i'm less focus because the same 
google () 
jcenter ()

**Comment by aldsho** [comment]
hello
i have same problem too i've replaced the {version} with latest version 2.6.16 but error appear unable to resolve dependency
This is my build.gradel all projects
repositories {
        google()
        jcenter()
        maven { url  "http://dl.bintray.com/jeancsanchez/maven" }

    

and that's my build.gradel(app)

dependencies {

    implementation "com.github.jeancsanchez:JcPlayer:2.6.16"

**Comment by jeancsanchez** [comment]
@aldsho I'm using Jitpack right now. So use this instead:
```
repositories {
    google()
    jcenter()
    maven { url "https://jitpack.io" }
}
```

**Comment by abhishek-singh-a4** [comment]
repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
    }

**Comment by abhishek-singh-a4** [comment]
implementation 'com.github.jeancsanchez:JcPlayer:2.6.16'
ERROR: Failed to resolve: com.github.jeancsanchez:JcPlayer:2.6.16
Show in Project Structure dialog
Affected Modules: app


please sir solve it

**Comment by senshiyaarora** [comment]
Failed to resolve: com.github.jeancsanchez:JcPlayer:2.7.0. Facing issue.

used implementation 'com.github.jeancsanchez:JcPlayer:2.7.0'
