### ISSUE TITLE
Could not resolve com.github.jeancsanchez:JcPlayer:2.7.2 (may be similar to #139)

### ISSUE THREAD

**Issue by Okuro3499** [jeancsanchez/JCPlayer#140]
I have integrated this library in a  project (https://github.com/open-learning-exchange/myplanet.git) and it was working fine and building succesfully in the github Android Check CI and it failed suddenly and I keep getting this Could not find com.github.jeancsanchez:JcPlayer:2.7.2. error.

I have added maven { url 'https://jitpack.io' } in project level build.gradel file and implementation 'com.github.jeancsanchez:JcPlayer:2.7.2' in app level build.gradle file.

![Screenshot from 2023-05-24 22-47-02](https://github.com/jeancsanchez/JcPlayer/assets/64019708/916b667d-85d4-49ae-83d6-ea8a5df74342)

**To Reproduce**
1. Go to 'https://github.com/open-learning-exchange/myplanet.git'
2. Click on 'Actions'
3. Select any of these 
![image](https://github.com/jeancsanchez/JcPlayer/assets/64019708/fbbaf5ac-ffa3-4ad2-adfb-3d8e247b6737)
and re-run jobs 
4. See error in logs

Kindly assist resolve this

**Comment by jeancsanchez** [comment]
Hello @Okuro3499 
Thanks for reporting. I will take a look at it as soon as possible.

**Comment by Mori-hub** [comment]
```
* What went wrong:
Execution failed for task ':app:dataBindingMergeDependencyArtifactsRelease'.
> Could not resolve all files for configuration ':app:releaseCompileClasspath'.
   > Failed to transform JcPlayer-2.7.2.aar (com.github.jeancsanchez:JcPlayer:2.7.2) to match attributes {artifactType=android-databinding, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-api}.
      > Could not find JcPlayer-2.7.2.aar (com.github.jeancsanchez:JcPlayer:2.7.2).
        Searched in the following locations:
            https://jitpack.io/com/github/jeancsanchez/JcPlayer/2.7.2/JcPlayer-2.7.2.aar
            https://jitpack.io/com/github/jeancsanchez/JcPlayer/2.7.2/JcPlayer-2.7.2.jar
```

**Comment by jeancsanchez** [comment]
Hello guys! 
For some reason, Jitpack repository did not create artifacts for the 2.7.2 version. 
I just forced a rebuild and I think it is ok now.  
Could you test it again?

**Comment by Mori-hub** [comment]
It's working now, 
Thank you ! @jeancsanchez

**Comment by Okuro3499** [comment]
It works ok now. I also found https://jitpack.io/p/jeancsanchez/jcplayer and it also worked ok
