### ISSUE TITLE
CallBacks?

### ISSUE THREAD

**Issue by ziadkiwan** [jeancsanchez/JcPlayer#17]
Hello is there any callback for the list view ? like on long press click on the list ? thank you.

**Comment by jeancsanchez** [comment]
@ziadkiwan The list view is an independent part, the JcPlayer library only care about the audio files and manipulating them. The lógic of list view is for the developer responsibility.

**Comment by ziadkiwan** [comment]
oh the application do not take care of creating the list too ? i need to create the adapter etc... ?

**Comment by jeancsanchez** [comment]
@joielechong yep 😃

**Comment by ziadkiwan** [comment]
oh okay got it thank you! you should mention that in the readme 👍

**Comment by jeancsanchez** [comment]
Thanks! I'll do it right now.
