### ISSUE TITLE
unable to unbind service when notification is clicked?

### ISSUE THREAD

**Issue by shivam21** [jeancsanchez/JcPlayer#18]

**Comment by jeancsanchez** [comment]
Call `kill()` method.

**Comment by shivam21** [comment]
calling kill method stops the song.Actually,I want that when a user clicks on notification activity starts and jcPlayerView starts from same time from which notification had left.

**Comment by jeancsanchez** [comment]
Sorry, the library doesn't offer a method to do this. I advise you cancel manually when the activity the notification starts. 
Some like this:
```java
 notificationManager.cancel(JcNotificationPlayer.NOTIFICATION_ID);
```
