### ISSUE TITLE
NullPointerException while trying to inflate UI component in xml

### ISSUE THREAD

**Issue by EseCoder** [jeancsanchez/JcPlayer#19]
Adding the custom JcPlayerView to my project throws a nullpointerexception as it cannot inflate UI component. Here is the error.

Exception Details java.lang.NullPointerException   at com.example.jean.jcplayer.JcPlayerView.init(JcPlayerView.java:69)   at com.example.jean.jcplayer.JcPlayerView.<init>(JcPlayerView.java:50)   at java.lang.reflect.Constructor.newInstance(Constructor.java:422)   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)   at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:835)   at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   at android.view.LayoutInflater.rInflate(LayoutInflater.java:811)   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)   at android.view.LayoutInflater.inflate(LayoutInflater.java:515)   at android.view.LayoutInflater.inflate(LayoutInflater.java:394)
...

Here is how I added the UI component:
<com.example.jean.jcplayer.JcPlayerView
        android:id="@+id/reminder_media_player"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

**Comment by joielechong** [comment]
How did you accessing the JcPlayerView, please post some code relevant to it.

**Comment by EseCoder** [comment]
Here is how I added the UI component:
<com.example.jean.jcplayer.JcPlayerView
android:id="@+id/reminder_media_player"
android:layout_width="match_parent"
android:layout_height="wrap_content" />

**Comment by EseCoder** [comment]
I added the library's .aar as a module. This is the only method that works for me.

**Comment by jeancsanchez** [comment]
@EseCoder I didn't see any problem with the library. Maybe it was thrown by some IDE bug. Generally, when it occur, a "clean project" often solves. All here seems working fine. 
How you solved your problem, I going to close this issue. If you need again, reopen it.

**Comment by saqibkafeel** [comment]
facing same NullPointerException issue ! any idea?

![image](https://cloud.githubusercontent.com/assets/6615261/24444978/34d28680-141d-11e7-8556-e96cee4eb162.png)

above is my gradle view and side my project structure !

**Comment by saqibkafeel** [comment]
![image](https://cloud.githubusercontent.com/assets/6615261/24445350/78eaddee-141e-11e7-91c7-20f8ee21c3d9.png)

**Comment by OmarNaji** [comment]
**Dear all,  jean,

facing same issue and i don't know why in the xml there is no Jcplayer.**

![0](https://user-images.githubusercontent.com/54332504/63380376-77e59480-c3a7-11e9-925b-9a9acfb0470d.PNG)
![1](https://user-images.githubusercontent.com/54332504/63380383-7a47ee80-c3a7-11e9-81df-02b865067841.PNG)
![2](https://user-images.githubusercontent.com/54332504/63380387-7c11b200-c3a7-11e9-8dbe-8858ac269106.PNG)
![3](https://user-images.githubusercontent.com/54332504/63380392-7d42df00-c3a7-11e9-8066-eb2e81e998d0.PNG)
![4](https://user-images.githubusercontent.com/54332504/63380397-7f0ca280-c3a7-11e9-9154-7c0b2e1807ff.PNG)


**Any Help Please.
Best Regards and thank you.**
