### ISSUE TITLE
does this work with files?

### ISSUE THREAD

**Issue by Xstar97** [jeancsanchez/JcPlayer#2]
I didn't see any docs about just using files...so does your library accept local audio files?

**Comment by jeancsanchez** [comment]
No yet. But I working about it 😺

**Comment by Xstar97** [comment]
Awesome, keep up the good work!

**Comment by joielechong** [comment]
@Xstar97: I've slightly modified the code to support local file as in issue #9. How do you think about that?

**Comment by Xstar97** [comment]
@joielechong
Awesome can't wait to test it out later!

**Comment by jeancsanchez** [comment]
@Xstar97  Well, you can now upgrade your version for 2.6.0-alpha. Thanks @joielechong
