### ISSUE TITLE
Unable to create Notification

### ISSUE THREAD

**Issue by digiwizkid** [jeancsanchez/JcPlayer#21]
Working perfectly, but I am not getting any notification while playing audio.

       `jcplayerView = (JcPlayerView) findViewById(R.id.jcplayer);

        String mp3 = getIntent().getStringExtra("content");
        String mp3_title = getIntent().getStringExtra("title");

        jcplayerView.createNotification(); // default icon

        ArrayList<JcAudio> jcAudios = new ArrayList<>();
        jcAudios.add(JcAudio.createFromURL(mp3_title, mp3));
        jcplayerView.initPlaylist(jcAudios);`

**Comment by jeancsanchez** [comment]
You should to call the method `createNotification()`, after `initPlaylist(jcAudios)`
I suggest you creating notification on `onStop()` method.
