### ISSUE TITLE
MediaPlayer error

### ISSUE THREAD

**Issue by digiwizkid** [jeancsanchez/JcPlayer#22]
Getting
`E/MediaPlayer: Should have subtitle controller already set`
and
`AudioFeedActivity has leaked ServiceConnection com.example.jean.jcplayer.JcAudioPlayer$1@422d1740 that was originally bound here`

while exiting from the app

**Comment by jeancsanchez** [comment]
I really don't know how fix this issue. I'll investigate more...

**Comment by jeancsanchez** [comment]
Please, try to call `jcplayer.kill();` on your `onDestroy()` method.

**Comment by jeancsanchez** [comment]
Duplicate of #79
