### ISSUE TITLE
Error on intiPlaylist and play next

### ISSUE THREAD

**Issue by Spiderbezno** [jeancsanchez/JcPlayer#23]
W/System.err: java.lang.IndexOutOfBoundsException: Index: 9, Size: 9
W/System.err:     at java.util.ArrayList.get(ArrayList.java:411)
W/System.err:     at com.example.jean.jcplayer.JcAudioPlayer.nextAudio(JcAudioPlayer.java:95)
W/System.err:     at com.example.jean.jcplayer.JcPlayerView.next(JcPlayerView.java:161)
W/System.err:     at com.example.jean.jcplayer.JcPlayerView.onClick(JcPlayerView.java:213)
W/System.err:     at android.view.View.performClick(View.java:5637)
W/System.err:     at android.view.View$PerformClick.run(View.java:22429)
W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err:     at android.os.Looper.loop(Looper.java:154)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by Spiderbezno** [comment]
I add 9 mp3 with this code
 for (int i = 0; i < results.size(); i++) {
            jcAudios.add(JcAudio.createFromAssets(results.get(i).getTitle(),
                results.get(i).getTitle() + ".mp3"));
          }
          jcPlayerView.initPlaylist(jcAudios);
          jcPlayerView.registerInvalidPathListener((MainActivity) getActivity());

**Comment by jeancsanchez** [comment]
@Spiderbezno You must interact with your loop decreasing -1 on size list. In another words, `results.size() -1 `
I think that's it :)

**Comment by Spiderbezno** [comment]
But if I do that My last element won't be present in the playlist will it??

**Comment by Spiderbezno** [comment]
NOw if i use result.size() -1

java.lang.IndexOutOfBoundsException: Index: 8, Size: 8
02-24 18:58:03.503 3674-3674/ad.aplication.mji.babynanas W/System.err:     at java.util.ArrayList.get(ArrayList.java:411)
02-24 18:58:03.503 3674-3674/ad.aplication.mji.babynanas W/System.err:     at com.example.jean.jcplayer.JcAudioPlayer.nextAudio(JcAudioPlayer.java:95)
02-24 18:58:03.503 3674-3674/ad.aplication.mji.babynanas W/System.err:     at com.example.jean.jcplayer.JcPlayerView.next(JcPlayerView.java:161)
02-24 18:58:03.503 3674-3674/ad.aplication.mji.babynanas W/System.err:     at com.example.jean.jcplayer.JcPlayerView.onClick(JcPlayerView.java:213)
02-24 18:58:03.503 3674-3674/ad.aplication.mji.babynanas W/System.err:     at android.view.View.performClick(View.java:5637)
02-24 18:58:03.503 3674-3674/ad.aplication.mji.babynanas W/System.err:     at android.view.View$PerformClick.run(View.java:22429)
02-24 18:58:03.503 3674-3674/ad.aplication.mji.babynanas W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
02-24 18:58:03.503 3674-3674/ad.aplication.mji.babynanas W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
02-24 18:58:03.504 3674-3674/ad.aplication.mji.babynanas W/System.err:     at android.os.Looper.loop(Looper.java:154)
02-24 18:58:03.504 3674-3674/ad.aplication.mji.babynanas W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
02-24 18:58:03.504 3674-3674/ad.aplication.mji.babynanas W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
02-24 18:58:03.504 3674-3674/ad.aplication.mji.babynanas W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
02-24 18:58:03.505 3674-3674/ad.aplication.mji.babynanas W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by Spiderbezno** [comment]
The behaviour strange. I use next button correctly for elements of the array to 0 for 3 but in the next it jump until the las elemnt??

**Comment by Spiderbezno** [comment]
and the  results.size() -1 I think is not necessary because var i never enter in the loop when the value is 9 because nine is not < 9

**Comment by jeancsanchez** [comment]
You right! 
Strange. The behavior of the next and previous button is when an IndexOutOfBound thrown, the player jump for the next audio of the list.
```java
 public void nextAudio() throws AudioListNullPointerException {
        if(playlist == null || playlist.size() == 0)
            throw new AudioListNullPointerException();

        else {
            if (currentJcAudio != null) {
                try {
                    JcAudio nextJcAudio = playlist.get(currentPositionList + position // 1);
                    this.currentJcAudio = nextJcAudio;
                    jcPlayerService.stop();
                    jcPlayerService.play(nextJcAudio);

                } catch (IndexOutOfBoundsException e) {
                    playAudio(playlist.get(0));
                    e.printStackTrace();
                }
            }

            updatePositionAudioList();
            playing = true;
            paused = false;
        }
    }

    public void previousAudio() throws AudioListNullPointerException {
        if(playlist == null || playlist.size() == 0)
            throw new AudioListNullPointerException();

        else {
            if (currentJcAudio != null) {
                try {
                    JcAudio previousJcAudio = playlist.get(currentPositionList - position // 1);
                    this.currentJcAudio = previousJcAudio;
                    jcPlayerService.stop();
                    jcPlayerService.play(previousJcAudio);

                } catch (IndexOutOfBoundsException e) {
                    playAudio(playlist.get(0));
                    e.printStackTrace();
                }
            }

            updatePositionAudioList();
            playing = true;
            paused = false;
        }
    }
```

**Comment by Spiderbezno** [comment]
This the behaviour always jump to first element, but I can next the first 2 elements before that always appear this error of IndexOutOfBoundsException

**Comment by Spiderbezno** [comment]
I do more test if my playlist have more than six elements it produce errors, with six elements o less all ok

**Comment by Spiderbezno** [comment]
are there some news??

**Comment by Spiderbezno** [comment]
Something new??

**Comment by Spiderbezno** [comment]
Is this library stopped?

**Comment by Spiderbezno** [comment]
Are the library stopped?

**Comment by sajorahasan** [comment]
Any update?

**Comment by jeancsanchez** [comment]
Sorry, I am not working properly on this library these months. This issue continues without a solution for now.
