### ISSUE TITLE
NOt see custom notification icon

### ISSUE THREAD

**Issue by Spiderbezno** [jeancsanchez/JcPlayer#26]
When I use this jcplayerView.createNotification(R.drawable.myIcon); // Your icon resource
I only see a square with any icon, are there any restriction in the drawable??

**Comment by jeancsanchez** [comment]
What API?

**Comment by Spiderbezno** [comment]
Sorry, in he JCPLayer?? I try tu put a custom icon notification but I can't see any thing

**Comment by jeancsanchez** [comment]
What the target API of your application. It depends on what target API you are developing. Please, see this answer. 
http://stackoverflow.com/questions/30795431/icon-not-displaying-in-notification-white-square-shown-instead

**Comment by Spiderbezno** [comment]
My target API is 25, and my icon is transparent

**Comment by arsalankhan994** [comment]
can u please tell me how to show list view.
