### ISSUE TITLE
Remove Notification when App is killed

### ISSUE THREAD

**Issue by yusufceylan** [jeancsanchez/JcPlayer#28]
I am creating notification in onStop but when user killed the app, notification still exist and causes a crash if you click it. is it possible to remove notification when app is killed?

```
    @Override
    protected void onStop() {
        super.onStop();
        // Create notification
        jcplayerView.createNotification();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        // Destroy notification
    }
```

**Comment by jeancsanchez** [comment]
This answer can help you #22

**Comment by yusufceylan** [comment]
@jeancsanchez still same. I added `jcplayerView.kill()` in my `onDestroy` method but notification does not removed when app is killed
