### ISSUE TITLE
Support Assets, and Raw files

### ISSUE THREAD

**Issue by iballan** [jeancsanchez/JcPlayer#3]
you may support to play files from assets and raw folders as well

**Comment by jeancsanchez** [comment]
Yes, I am working about that. Feel free to contribute too 😄

**Comment by joielechong** [comment]
@iballan: I've slightly modified the library to accept raw and asset files as in issue #9. Is the solution good?. Thank you.

**Comment by jeancsanchez** [comment]
Please see the issue #2
