### ISSUE TITLE
player.kill() method does not clear notification

### ISSUE THREAD

**Issue by djsbaa** [jeancsanchez/JcPlayer#31]
When I kill the app it should clear the notification unfortunately does not; the app destroyed but the notification still shown, when I click one of its  buttons (previous, pause/play or next) the app raises an NullExceptionError  on `jcPlayerNotificationReceiver.java` [here](https://github.com/jeancsanchez/JcPlayer/blob/master/jcplayer/src/main/java/com/example/jean/jcplayer/JcPlayerNotificationReceiver.java#L22)

Info:
-I test it on Android 7.0
-App's configuration still as its in this library (not changed).

Any suggestion that can help fix the issue!

**Comment by damitha1** [comment]
i also get the same error mentioned above.please help to fix the issue!

**Comment by djsbaa** [comment]
Check if player not null if its clear notification by your self

**Comment by damitha1** [comment]
thank for your reply yes i check this method
  if(jcAudioPlayer != null){
            return true;
        }else{
            return fals;
        }
 in JcPlayerNotificationReceiver class but how can clear notification  return false?
can you help me..

**Comment by djsbaa** [comment]
You nee to find NOTIFICATION_ID in the project 
protected void onExit() {
    notificationManager.cancel(NOTIFICATION_ID);
}

**Comment by damitha1** [comment]
@djsbaa Thank you in which i want to do that?
protected void onExit() {
notificationManager.cancel(NOTIFICATION_ID);
}
