### ISSUE TITLE
Attempt to invoke virtual method play on a null object reference

### ISSUE THREAD

**Issue by Ajrulovski** [jeancsanchez/JcPlayer#33]
Hello,

I am testing your library with a simple code

        JcPlayerView jcplayerView = (JcPlayerView) findViewById(R.id.jcplayer);
        ArrayList<JcAudio> jcAudios = new ArrayList<>();
        jcAudios.add(JcAudio.createFromFilePath("Asset audio", "/sdcard/Download/"+audioname));
        jcplayerView.initPlaylist(jcAudios);

        jcplayerView.playAudio(jcplayerView.getMyPlaylist().get(0));

And if I comment out the last line, a player shows in the activity and works awesome. However if i leave the line uncommented I get Attempt to invoke virtual method 'void com.example.jean.jcplayer.JcPlayerService.play(com.example.jean.jcplayer.JcAudio)' on a null object reference. The object I am referencing is not null, I checked that. What I am trying to do here is to autoplay the audio. Any idea why this is so? I am writing here as it seems to be a bug.

BTW, love the library.

Very best regards.

**Comment by cartproduction** [comment]
I am getting this error too and I try everything about that I didn't fixed yet.

**Comment by jeancsanchez** [comment]
This error happens because when initializing a playlist and next play an audio, the service is not ready yet, so a `NullPointerException` is thrown. 
I am working to fix it, soon I release a new version.
Thank you for all :D

**Comment by jeancsanchez** [comment]
⚠️   ⚠️   ⚠️  **WARN**  ⚠️   ⚠️   ⚠️ 
For versions > 2.6.0-alpha, I  have changed the repository to Jitpack repository. See the docs for more information. 
From this version the issue is solved: `com.github.jeancsanchez:JcPlayer:2.6.10'`
