### ISSUE TITLE
can't use multiple jcAudioPlayer in RecyclerView.

### ISSUE THREAD

**Issue by chenkexu** [jeancsanchez/JcPlayer#34]
I can't use multiple jcAudioPlayer in RecyclerView.
 Click events repeat

**Comment by jeancsanchez** [comment]
What did you mean with "multiple jcAudioPlayer" ? The JcAudioPlayer is a singleton object, once you initialize it, all configurations set before will be used anywhere.

**Comment by jeancsanchez** [comment]
I am closing this issue because I think you solve your problem.
If you need later, reopen it.
