### ISSUE TITLE
Manifest merger failed 

### ISSUE THREAD

**Issue by Saad-Mahmud** [jeancsanchez/JcPlayer#35]
When i try to add  compile 'io.github.jeancsanchez.jcplayer:jcplayer:0.0.2' it gives the following error
Manifest merger failed : Attribute application@icon value=(@mipmap/ic_launcher_round) from AndroidManifest.xml:14:9-49 is also present at [io.github.jeancsanchez.jcplayer:jcplayer:0.0.2] AndroidManifest.xml:14:9-43 value=(@mipmap/ic_launcher). Suggestion: add 'tools:replace="android:icon"' to element at AndroidManifest.xml:11:5-65:19 to override.

**Comment by jeancsanchez** [comment]
Add to your manifest tag `xmlns:tools="http://schemas.android.com/tools"`
Then added `tools:replace="android:icon,android:theme"` to the application tag

This tells the merger to use your manifest icon and theme and not of the library.
Read this: https://stackoverflow.com/questions/24506800/android-studio-gradle-icon-error-manifest-merger

**Comment by jeancsanchez** [comment]
Please, tell me if it works.

**Comment by Saad-Mahmud** [comment]
Yeah, it works. Thanks a lot.
