### ISSUE TITLE
cant add it to dependencies

### ISSUE THREAD

**Issue by bagherhasani** [jeancsanchez/JcPlayer#38]
hello thanks for this cool music player
i really cant add it to dependencies
compile 'io.github.jeancsanchez.jcplayer:jcplayer:{version}'
when i set 0.0.2 instead of {version} it fails 
and the same when i set it to 3.3
please create another new simple project with clear dependencies

**Comment by AlaaZarifa** [comment]
@bagherhasani  here


```
allprojects {
    repositories { 
        maven {  url  "http://dl.bintray.com/jeancsanchez/maven" }
    }
}
```

` compile 'io.github.jeancsanchez.jcplayer:jcplayer:2.6.0-alpha'
`

**Comment by bagherhasani** [comment]
okay
i really appreciate it

**Comment by jeancsanchez** [comment]
⚠️ ⚠️ ⚠️ WARN ⚠️ ⚠️ ⚠️
For versions > 2.6.0-alpha, I have changed the repository to Jitpack repository. See the docs for more information.
