### ISSUE TITLE
The music list not showing

### ISSUE THREAD

**Issue by DevilLordAero** [jeancsanchez/JcPlayer#40]
First Problem : it just show the control (backward,forward,pause,duration and title)
There no music list like in your picture (awesome music 1, awesome music 2) based in my code, this should add "Another One Bities Of Dust","Be Starters","Gee,"Crazy Frogs" etc to the music list and show it right?

Second Problem: the music is played properly, but when i keep forward the audio, it just play till "Feel This Moment" 6 more audio are not added to the playlist, but in code , i added it, why?

My apk : https://ufile.io/0ycnh sorry if i upload here

code : 
player = (JcPlayerView)findViewById(R.id.musicplayer);
        ArrayList<JcAudio> musicList = new ArrayList<JcAudio>();
        musicList.add(JcAudio.createFromURL("Another One Bities Of Dust","https://s1.vocaroo.com/media/download_temp/Vocaroo_s1zqcwflJjFT.mp3"));
        musicList.add(JcAudio.createFromURL("Be Starters","https://s1.vocaroo.com/media/download_temp/Vocaroo_s1KMVtNBwtGW.mp3"));
        musicList.add(JcAudio.createFromURL("Crazy Frogs","https://s1.vocaroo.com/media/download_temp/Vocaroo_s1IN5m15oEcu.mp3"));
        musicList.add(JcAudio.createFromURL("Dance Of The Knights","https://s1.vocaroo.com/media/download_temp/Vocaroo_s1UtUmVB1Tl2.mp3"));
        musicList.add(JcAudio.createFromURL("Dumags","https://s1.vocaroo.com/media/download_temp/Vocaroo_s1CcypsYOiS7.mp3"));
        musicList.add(JcAudio.createFromURL("Feel This Moment","https://s1.vocaroo.com/media/download_temp/Vocaroo_s1AfxoRr8dk3.mp3"));
        musicList.add(JcAudio.createFromURL("Flight Of The Bumblebee","https://s1.vocaroo.com/media/download_temp/Vocaroo_s15cjibddJl2.mp3"));
        musicList.add(JcAudio.createFromURL("Game of Thrones","https://s1.vocaroo.com/media/download_temp/Vocaroo_s1srPoxtfSeA.mp3"));
        musicList.add(JcAudio.createFromURL("Gee","https://s1.vocaroo.com/media/download_temp/Vocaroo_s14Lx19MsFxa.mp3"));
        musicList.add(JcAudio.createFromURL("Growtopia Menu","https://s1.vocaroo.com/media/download_temp/Vocaroo_s1RU8xv4uosK.mp3"));
        musicList.add(JcAudio.createFromURL("Here With You","https://s1.vocaroo.com/media/download_temp/Vocaroo_s1R52lycmdAp.mp3"));
        musicList.add(JcAudio.createFromURL("Hey There Darlin","https://s1.vocaroo.com/media/download_temp/Vocaroo_s1qZzHc11Ybl.mp3"));
        musicList.add(JcAudio.createFromURL("I Need Your Love","https://s1.vocaroo.com/media/download_temp/Vocaroo_s1AJ93YXmOnN.mp3"));
        player.initWithTitlePlaylist(musicList,"Growtopia Music");

**Comment by jeancsanchez** [comment]
Is that solved?

**Comment by DevilLordAero** [comment]
solve
