### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by DevilLordAero** [jeancsanchez/JcPlayer#41]
12-27 17:11:56.020 E/AndroidRuntime(24331): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.animation.AnimatorCompatHelper" on path: DexPathList[[zip file "/data/app/org.redeagle.gtmusic-1/base.apk"],nativeLibraryDirectories=[/data/app/org.redeagle.gtmusic-1/lib/arm64, /system/lib64, /vendor/lib64]]
 - My admob banner not showing
 - Crashed with the report that ^(above)
Details : crash after application open and the music start playing
My src :https://drive.google.com/file/d/1P-O9OKDkxQ-PcKlQKofuXbYxS4NSJSJF/view?usp=sharing

**Comment by jeancsanchez** [comment]
Please, give more details about the crash.

**Comment by DevilLordAero** [comment]
wait i suddenly entered this when i typing

**Comment by DevilLordAero** [comment]
There is.

**Comment by jeancsanchez** [comment]
Why don't you upload your source code to Github instead of Google Drive :D ?

**Comment by DevilLordAero** [comment]
Ok ill upload it to github

**Comment by DevilLordAero** [comment]
i cant upload to github, it say to much file, try fewer than 100.
where can i upload for you except github?

**Comment by jeancsanchez** [comment]
Weird. I can't download it from the computer that I'm working now :/  It will be hard to help you if I can't see your code. 
But I think the problem is on the Admob library. Have you tried clean the project?

**Comment by DevilLordAero** [comment]
i clean the project already

**Comment by DevilLordAero** [comment]
should i upload to other service? i really need help in this application.

**Comment by jeancsanchez** [comment]
You can try upload to [Bitbucket](https://bitbucket.org/) and share the code with me, but I advise you try to solve the problem with the Github.

**Comment by DevilLordAero** [comment]
I don't understand GitHub so much, I upload it via web and drag the project folder xD. I'll try to upload to bitbucket

**Comment by DevilLordAero** [comment]
Here is, if there missing file, tell me https://github.com/DevilLordAero/GT-Music/

**Comment by jeancsanchez** [comment]
I've seen your code and your problem is not with JcPlayer library, your problem is with Admob library, please look with more attention the log cat error, you don't initializing the Admob library correctly ` java.lang.IllegalStateException: The ad size and ad unit ID must be set before loadAd is called.`  :D

**Comment by DevilLordAero** [comment]
I already set the ad unit id in my code, i just remove them from the code that i have uploaded.

**Comment by DevilLordAero** [comment]
<com.google.android.gms.ads.AdView
        xmlns:ads="http://schemas.android.com/apk/res-auto"
        android:id="@+id/ads"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentTop="true"
        android:layout_centerHorizontal="true"
        ads:adSize="SMART_BANNER"
        ads:adUnitId="cap-app-pub-2071995991481817/3186188352"></com.google.android.gms.ads.AdView>

super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        MobileAds.initialize(this,"ca-app-pub-2071995991481817~2927044347");
        adView = findViewById(R.id.ads);
        interAds = new InterstitialAd(this);
        interAds.setAdUnitId("ca-app-pub-2071995991481817/3797272881");
        AdRequest adRequest = new AdRequest.Builder().build();
        adView.loadAd(adRequest);

**Comment by jeancsanchez** [comment]
You can't post this id here bro 0_0 this is confidential. How I sad, your are having problems with [Admob](https://www.google.com/admob/?gclid=CjwKCAiApo3SBRA4EiwAty8i-iGl8dMnnBt2Sjze7OywIojOPQBpvhgy088Vq357SAyZ9R63-SUAshoCc7IQAvD_BwE&gclsrc=aw.ds&dclid=CMz8mrScqtgCFQgQhwodvTgG_A) library, please only open issues about the JcPlayer library. Thank you.

**Comment by DevilLordAero** [comment]
Can you tell me how to fix it?

**Comment by jeancsanchez** [comment]
Sorry :/

**Comment by DevilLordAero** [comment]
Nope, my bad I'll looking solution for it

**Comment by DevilLordAero** [comment]
No, it was the library problem, I removed all of the admob code, it still crashed.

**Comment by DevilLordAero** [comment]
I even not import any admob class to my activity and I also remove the banner adview from xml.
Is there a problem with my manifest?

**Comment by DevilLordAero** [comment]
Hello? Can you help me
