### ISSUE TITLE
setLooping(true) ???

### ISSUE THREAD

**Issue by mehyaz** [jeancsanchez/JcPlayer#43]
How can I set an audio in loop?

**Comment by mehyaz** [comment]
Is there anyone to help?

**Comment by peace-shillong** [comment]
Hey @mehyaz , Is it something like repeat song, 
currently if you add songs to the playlist, and the playlist reaches the end of the list, by default it starts playing the list from the start, which is kind a like repeat all songs in the list.
You can take a look at JcAudioPlayer.java in line 114 the nextAudio() funtion you will see in line 126 : playAudio(playlist.get(0)); 
which means that if there is an exception like u reached something like the end of the list, it starts playing from the begining again.

If you want to work on this, here is a small suggestion you can start off with

**Logic/Algorithm to get Working with the Repeat Funtion** 
1. We will need a String field variable "repeatMode" in the JcAudioPlayer class which can be set to NONE/ALL/ONE  by default it can be ALL. This varaible tells us whether we are Looping the Playlist or not.
2. Have a button on the PlayerView layout XML with appropriate icons and assign them to the respective repeat button "repeatBtn" just like the play/prev/next button. and in the Listener repeatBtn.setOnClickListener - on Click of the button Check the current State of the repeatMode and change it accordingly. **LOOK AT point 4.**
3. Now in the nextAudio() inside the JcAudioPlayer class checkout line 120: JcAudio nextJcAudio = playlist.get(currentPositionList + position);

before doing this do something like this
if(repeatMode.equals("NONE")||repeatMode.equals("ALL"))
{
   JcAudio nextJcAudio = playlist.get(currentPositionList + position);
 // this means as usual just play the next audio
}
else if(repeatMode.equals("ONE"))
{
  JcAudio nextJcAudio = playlist.get(currentPositionList);
 // this means repeat the audio
}


Now in the exception block
line 126: playAudio(playlist.get(0));
do this 
if(repeatMode.equals("ALL"))
{
 playAudio(playlist.get(0));
//repeat all the songs in the list
}
else
{
  jcPlayerService.stop();
// don't repeat the list
}


//String currentRepeatMode="ALL"; declare this somewhere
4. You can create a public method setLooping(String mode) inside the JcAudioPlayer class and call it on the click of the repeat button
inside the handler for the repeatBtn onClickListener

if(currentRepeatMode.equals("ALL"))
{
    currentRepeatMode="NONE";
    setLooping(currentRepeatMode);
}
else if(currentRepeatMode.equals("NONE"))
{
   currentRepeatMode="ONE";
   setLooping(currentRepeatMode);
}
else
{
  currentRepeatMode="ALL";
  setLooping(currentRepeatMode);
}

DONE...HOPE THIS COULD GIVE EVERYONE AN IDEA ON WORKING WITH LOOPING AUDIO IN THE PLAYLIST>>

@jeancsanchez please take a look at this also..it might be helpful, Thank You.
