### ISSUE TITLE
Cache Audio from url, and play without internet

### ISSUE THREAD

**Issue by peace-shillong** [jeancsanchez/JcPlayer#44]
Hey there guys, I want to play audio files from the internet using jcplayer. I know it is possible with the function createFromURL() can anyone tell me how do I cache the song played from url and store it on the apps private cache, so that later I can retrieve it from the cache without internet connectivity.
This could be really useful to me to allow users to play songs without internet, once they have played/downloaded the song once when the are connected, later they can play without internet,

**Comment by peace-shillong** [comment]
@jeancsanchez  I have been working on this the last few weeks to test this feature out. I was able to do it by following the steps below:
**If a user wants to play an audio file from Url instead of Passing the Url of the server online, I passed the Url of the cached data in the createFromUrl(), I have edited the sample project to try this out.**

1. Created a Class called Downloader that downloads the song to cache dir of the app.
2. In the MainActivity, I created an anonymous object of the Downloader class and pass the Cache Dir of the App
3. in the Downloader Class, I have a method that downloads the song to the cache
4. Once the song is in cache I createFromUrl by passing the cahce dir in the url, in the MainActivity.

and it works,

Limitations and Further enhancement that can be done:
1. Player waits until song is downloaded then Starts Playing the songs.
1. I Did not do a check on if File Exists in cache so right now it downloads the song then play it everytime the player is loaded: enhancement would be to check if file exists in cache then don't download file, just play it directly.
1. Note: In the MainActivity: the object is Created in a Thread, since i cannot make network connections in the Main UI: enhancement would be to have a better way if possible to cache the song outside the MainActivity.

## CODE:

**MainActivity.java**
songurl="http://127.0.0.1/songs/";
filename="title.mp3";
//ADDED DOWNLOADS
try{
  int SDK_INT = android.os.Build.VERSION.SDK_INT;
  if (SDK_INT > 8)
   {
            StrictMode.ThreadPolicy policy = new StrictMode.ThreadPolicy.Builder()
                    .permitAll().build();
            StrictMode.setThreadPolicy(policy);   
            new Downloader(getCacheDir(),songurl,filename); 
   }
            jcAudios.add(JcAudio.createFromFilePath("in Cache",getCacheDir().toString()+"/"+filename));
   }
catch(Exception e) { e.printStackTrace(); }

**Downloader.java**

import android.util.Log;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * Created by Peace on 27/03/2018.
 */

public class Downloader  {
    public Downloader(File getDir, String songurl,String filename)
    {
        download(getDir,songurl,filename);
    }
    private void download(File getDir, String songurl,String filename) {
        try {
            //set the download URL, a url that points to a file on the internet
            URL url = new URL(songurl+""+filename);

            //create the new connection
            HttpURLConnection urlConnection = (HttpURLConnection) url.openConnection();

            //set up some things on the connection
            urlConnection.setRequestMethod("GET");
            urlConnection.setDoOutput(true);

            //and connect!
            urlConnection.connect();

            //set the path where we want to save the file
            File SDCardRoot = getDir;          
            //create a new file, specifying the path, and the filename
            //which we want to save the file as.
            File file = new File(SDCardRoot,filename);
           // Log.d("LOG","DIR Store "+SDCardRoot + file);

            //this will be used to write the downloaded data into the file we created
            FileOutputStream fileOutput = new FileOutputStream(file);

            //this will be used in reading the data from the internet
            InputStream inputStream = urlConnection.getInputStream();

            //this is the total size of the file
            int totalSize = urlConnection.getContentLength();
            //variable to store total downloaded bytes
            int downloadedSize = 0;

            //create a buffer...
            byte[] buffer = new byte[1024];
            int bufferLength = 0; //used to store a temporary size of the buffer

            //now, read through the input buffer and write the contents to the file
            while ( (bufferLength = inputStream.read(buffer)) > 0 ) {
                //add the data in the buffer to the file in the file output stream (the file on the sd card
                fileOutput.write(buffer, 0, bufferLength);
                //add up the size so we know how much is downloaded
                downloadedSize += bufferLength;
                //this is where you would do something to report the prgress, like this maybe
                updateProgress(downloadedSize, totalSize);

            }
            //close the output stream when done
            fileOutput.close();

//catch some possible errors...
        } catch (MalformedURLException e) {
            e.printStackTrace();
            //Toast.makeText(this," E"+e,Toast.LENGTH_SHORT).show();         
        } catch (IOException e) {
            e.printStackTrace();
//            Toast.makeText(this,"2 E"+e,Toast.LENGTH_SHORT).show();
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }

    private void updateProgress(int downloadedSize, int totalSize) {
        Log.d("DOWNLOADER","done " +downloadedSize+ " Total "+totalSize);
    }
}

**Comment by jeancsanchez** [comment]
Good job :D
