### ISSUE TITLE
Support local files

### ISSUE THREAD

**Issue by janyksteenbeek** [jeancsanchez/JcPlayer#5]
Right now, the library does not support local file storage. This, of course, should be a thing that is essential to such a library. Are there any plans on supporting this?

Is there any way to override the URL checker?

**Comment by jeancsanchez** [comment]
Yes Janyk, we are working on this feature, very soon the library will support local files too.

**Comment by kiyos88** [comment]
it supports if you start the file path as file:///

**Comment by janyksteenbeek** [comment]
It does play them, yes @kiyos88. However, you cannot put them into a playlist, as the [url checker](https://github.com/jeancsanchez/JcPlayer/blob/master/jcplayer/src/main/java/com/example/jean/jcplayer/JcPlayerView.java#L195) does not allow this.

Thanks for the update @jeancsanchez, I'm looking forward to it.

**Comment by joielechong** [comment]
As in issue #9, I modified the code and temprary disable url checking for file. What your suggestion about url checking? How we do a better checking that allow file path?

**Comment by jeancsanchez** [comment]
Please see the issue #2

**Comment by sathishcanine** [comment]
Hi , i have some issue here , in  5.0 and above versions its not working.... it just loading ...finally getting not responding ...please give a solution 
Thanks in advance
