### ISSUE TITLE
soundpool

### ISSUE THREAD

**Issue by mehyaz** [jeancsanchez/JcPlayer#50]
Can you add soundpool to play simple sounds gapless to JcPlayer2. Mediaplayer class make gap in looping

**Comment by jeancsanchez** [comment]
Interesting, but I think that I don't get it correctly. Can you Explain more about your idea...

**Comment by mehyaz** [comment]
Dear Jean. I use MediaPlayer to playing loop background sounds in my app. The file is .ogg or mp3 audio format.

MediaPlayer mp1 = MediaPlayer.create(context, R.raw.track1); mp1.setLooping(true); // setting loop mp1.start();

there is a gap when the audio file loops.
I solved this problem using the soundpool class. But but soundpoll is a more restricted class than the mediaplayer. 
I want you to solve the gap problem in looping at JCplayer2.

**Comment by jeancsanchez** [comment]
Looks good. I am rewriting the library in Kotlin, you can send that pull request soon.
