### ISSUE TITLE
Question on the updateProgress in AudioAdapter Class from the Sample App

### ISSUE THREAD

**Issue by peace-shillong** [jeancsanchez/JcPlayer#52]
I have been trying out the sample app and checking it out and trying to help as much as I can, 
I have a question @jeancsanchez What does the updateProgress() function in line 98 inside the AudioAdapater class do in the Sample App?

for Your Reference I have pasted the function below:

public void updateProgress(JcAudio jcAudio, float progress) {
        int position = jcAudioList.indexOf(jcAudio);
        Log.d(TAG, "Progress = " + progress);
        progressMap.put(position, progress);
        if(progressMap.size() > 1) {
            for(int i = 0; i < progressMap.size(); i++) {
                if(progressMap.keyAt(i) != position) {
                    Log.d(TAG, "KeyAt(" + i + ") = " + progressMap.keyAt(i));
                    notifyItemChanged(progressMap.keyAt(i));
                    progressMap.delete(progressMap.keyAt(i));
                }
            }
        }
        notifyItemChanged(position);
    }

**Comment by peace-shillong** [comment]
After testing the sample app on android 7.0 I saw that this function actually displays a yellow background on the current song in the List, is there anyway to change only the Text color of the current song in the list instead of showing a yellow progress background?

**Comment by jeancsanchez** [comment]
@peace-shillong The list on the sample application is just an example. You can do your own list with your own logic.
