### ISSUE TITLE
this player not stop.

### ISSUE THREAD

**Issue by Mahdihp** [jeancsanchez/JcPlayer#54]
this player not stop evry. loop play track?

**Comment by jeancsanchez** [comment]
Not yet. Actually, you have to simulate these behaviors with the play(), pause(), next() and previous() methods.

**Comment by Mahdihp** [comment]
connot work Status listener for duretion ?

**Comment by jeancsanchez** [comment]
Yes, you can implement the interface   `JcPlayerView.JcPlayerViewStatusListener`. 
See the sample app on MainActivity.
