### ISSUE TITLE
Propose Logo/Icon

### ISSUE THREAD

**Issue by mirzazulfan** [jeancsanchez/JcPlayer#56]
Hi @jeancsanchez ,, I'm graphic disigner. I would like to know if you are interested that I make a logo for your project? If you allowed me, i"ll make logo for your project.

**Comment by jeancsanchez** [comment]
Feel free :D

**Comment by mirzazulfan** [comment]
Hi @jeancsanchez .. I've designed a logo for your project,, if you like it .. i'll make a pr. 
if you want some change i'll fix it. Thanks
V.1
![jcplayer](https://user-images.githubusercontent.com/36124339/42126795-87d200be-7cb7-11e8-9ef5-4c613f8aa39e.png)

**Comment by jeancsanchez** [comment]
I liked it so much. Thanks!!! Send me a pr.

**Comment by mirzazulfan** [comment]
Im glad you liked it,, i'll put it in Gdrive first and you can download all files (logotype, logo and editables file). :+1:
