### ISSUE TITLE
pause and seekbar not working

### ISSUE THREAD

**Issue by yeganehaym** [jeancsanchez/JcPlayer#59]
hey and thanks for this simple player for a fast solution
when i press the play button, pause button doesn't appear and spinner is showing
seek bar now working at all and cause stop audio

**Comment by peace-shillong** [comment]
@yeganehaym Play/Pause and Seekbar Works.
This happens When your audio file cannot be loaded by the player.
Please check: You have provided the correct location for the file and that the file is playable, Try with a different file.
Check out the sample project on how to play audio from phone storage.

**Comment by yeganehaym** [comment]
audio is playing and i can hear the vice
but control has problems

**Comment by peace-shillong** [comment]
Oh you mean seekbar controls?
I also have faced this kind of problem when i load mp3 files that are online.
The audio plays but I'm unable to move the seek bar.
But for the same file if i play it offline using localhost there is no problem and i can move the seek bar.

**Comment by jeancsanchez** [comment]
Hello guys. I'm not facing this problem yet 🤔 
Can you send the audio link for me to test it?

**Comment by peace-shillong** [comment]
I will send the mp3 files via email

**Comment by harunarrosyid** [comment]
same problem if i use url seek bar not work for all audio

**Comment by jeancsanchez** [comment]
@yeganehaym I recently released a new version of the library. Can you test it?
`com.github.jeancsanchez:JcPlayer:2.6.11`

**Comment by abhatnagar03** [comment]
I am still facing the issue in com.github.jeancsanchez:JcPlayer:2.6.11. Seekbar works only first time when I am loading the audio from a url. I can hear the audio play. 

Do you have any solution for this? Thanks.

**Comment by mstavares** [comment]
Hi @jeancsanchez  

I have the same problem described here. I'm using version 2.6.16, could you please help me?

Thanks
