### ISSUE TITLE
How to set the same title from recyclerview in player .?

### ISSUE THREAD

**Issue by rubinnellikunnathu** [jeancsanchez/JcPlayer#6]
Dear, First of all im thanking u so much for this awesome music player, u saved my time alot .
but i have a small doubt .
i have an arraylist of urls and titles. I am able to show the whole title in RecyclerView.
But,How can i show the selected title from recyclerview as the player header.

![device-2016-11-18-113049](https://cloud.githubusercontent.com/assets/13848574/20420664/36bee442-ad85-11e6-8c29-108f0ec0b5e0.png)

**Comment by rubinnellikunnathu** [comment]
I am Expecting something like this.

**## Option 3: Initialize an playlist with a custom title for all**

 ```
   ArrayList<String> urls = new ArrayList<>();
    urls.add("http://www.example.com.br/android/Music_01.mp3");
    urls.add("http://www.example.com.br/android/Music_02.mp3");

 ArrayList<String> titles = new ArrayList<>();
    titles.add("ABC Song");
    titles.add("BCD Song");

    jcplayerView.initWithTitlePlaylist(urls, titles);
```

# OR

Is their any way to get the current position , So that i can set the title by calling titles.get(position)

  ```
ArrayList<String> urls = new ArrayList<>();
    urls.add("http://www.example.com.br/android/Music_01.mp3");
    urls.add("http://www.example.com.br/android/Music_02.mp3");

 ArrayList<String> titles = new ArrayList<>();
   titles.add("ABC Song");
   titles.add("BCD Song");


    jcplayerView.initWithTitlePlaylist(urls, titles.get(position);
```

**Comment by jeancsanchez** [comment]
Hello friend :D

You can use a List of JcAudio objects. For example:
```java
List<JcAudio> audios  = new ArrayList<>();
audios.add(new JcAudio("http://www.example.com.br/Music_01.mp3", "My title 1"));
audios.add(new JcAudio("http://www.example.com.br/Music_02.mp3", "My title 2"));

player.initPlaylist(audios);
```

So, you implement your onClick function parsing a JcAudio with parameter and play it:
```java
public void onClick(JcAudio jcAudio){
    player.playAudio(jcAudio);
}
```
