### ISSUE TITLE
Does this works with Fragments

### ISSUE THREAD

**Issue by CristianSarac** [jeancsanchez/JcPlayer#7]
Like title says , in the demo app and readme only mentions Activity, will it work with Fragments?

**Comment by jeancsanchez** [comment]
Yes, normally.

**Comment by CristianSarac** [comment]
Ok cool , i see that you updated the readme to avoid further confusions 
Thanks

**Comment by VikasGutte** [comment]
@CristianSarac / @jeancsanchez : Did you tried with Fragments? If yes could you please share code? I was trying but it's not working, so many errors 😥. Mainly errors on `this` & `runOnUiThread` keyword, i tried replacing this with `getActivity()`/`getContext()` but not working.

Thank you in Advance...!

**Comment by jeancsanchez** [comment]
Can you share the code and logs?

**Comment by VikasGutte** [comment]
@jeancsanchez Thank you reply, kindly find below screenshot and code for your reference. 

Thank you for your help.

Have Nice Day...!

![image](https://user-images.githubusercontent.com/30354348/55279353-1c563400-533e-11e9-98f1-de309044e675.png)


    public class Fragment extends android.support.v4.app.Fragment {
    
    private JcPlayerView player;
    private RecyclerView recyclerView;
    private AudioAdapter audioAdapter;
    public static String[] titleArray = {
            "Google"
    };

    public static String[] playurl = {
            "https://google.com/abc.mp3",
            };


    @SuppressLint("ClickableViewAccessibility")
    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        @SuppressLint("InflateParams")
        View rootView = inflater.inflate(R.layout.fragment_layout, null, false);
        ImageView imageView = rootView.findViewById(R.id.navIcon);
        final MainActivity mainActivity = (MainActivity) getActivity();
        imageView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                assert mainActivity != null;
                mainActivity.drawerLayout.openDrawer(mainActivity.navView, true);
            }
        });

        recyclerView = rootView.findViewById(R.id.recyclerView);
        player = rootView.findViewById(R.id.jcplayer);

        ArrayList<JcAudio> jcAudios = new ArrayList<>();
        //Integer arrayLength = (Integer) url.length;
        for (int i = 0; i < titleArray.length; i++)
            jcAudios.add(JcAudio.createFromURL(titleArray[i], playurl[i]));


        player.initPlaylist(jcAudios, this);
        adapterSetup();

        return rootView;
    }

    @Override
    protected void onStop() {
        super.onStop();
        player.createNotification(R.mipmap.ic_launcher);
    }

    protected void adapterSetup() {
        audioAdapter = new AudioAdapter(player.getMyPlaylist());
        audioAdapter.setOnItemClickListener(new AudioAdapter.OnItemClickListener() {
            @Override
            public void onItemClick(int position) {
                player.playAudio(Objects.requireNonNull(player.getMyPlaylist()).get(position));
            }

            @Override
            public void onSongItemDeleteClicked(int position) {
                Toast.makeText(MainActivity.this, "Delete song at position " + position,
                        Toast.LENGTH_SHORT).show();
    //                if(player.getCurrentPlayedAudio() != null) {
    //                    Toast.makeText(MainActivity.this, "Current audio = " + player.getCurrentPlayedAudio().getPath(),
    //                            Toast.LENGTH_SHORT).show();
    //                }
                removeItem(position);
            }
        });
        LinearLayoutManager layoutManager = new LinearLayoutManager(this, LinearLayoutManager.VERTICAL, false);
        recyclerView.setLayoutManager(layoutManager);
        recyclerView.setAdapter(audioAdapter);

        ((SimpleItemAnimator) Objects.requireNonNull(recyclerView.getItemAnimator())).setSupportsChangeAnimations(false);

    }

    @Override
    public void onPause() {
        super.onPause();
        player.createNotification(R.mipmap.ic_launcher);
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        player.kill();
    }

    @Override
    public void onPathError(@NotNull JcAudio jcAudio) {
        Toast.makeText(this, jcAudio.getPath() + " with problems", Toast.LENGTH_LONG).show();
    //        player.removeAudio(jcAudio);
    //        player.next();
    }


    @Override
    public void onPreparedAudio(@NotNull JcStatus status) {

    }

    @Override
    public void onCompletedAudio() {

    }

    @Override
    public void onPaused(@NotNull JcStatus status) {

    }

    @Override
    public void onContinueAudio(@NotNull JcStatus status) {

    }

    @Override
    public void onPlaying(@NotNull JcStatus status) {

    }

    @Override
    public void onTimeChanged(@NonNull JcStatus status) {
        updateProgress(status);
    }

    @Override
    public void onJcpError(@NonNull Throwable throwable) {
        Toast.makeText(this, throwable.getMessage(), Toast.LENGTH_LONG).show();
    }

    private void updateProgress(final JcStatus jcStatus) {

        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                // calculate progress
                float progress = (float) (jcStatus.getDuration() - jcStatus.getCurrentPosition())
                        / (float) jcStatus.getDuration();
                progress = 1.0f - progress;
                audioAdapter.updateProgress(jcStatus.getJcAudio(), progress);
            }
        });
    }

    private void removeItem(int position) {
        ((SimpleItemAnimator) Objects.requireNonNull(recyclerView.getItemAnimator())).setSupportsChangeAnimations(true);

        //        jcAudios.remove(position);
        player.removeAudio(Objects.requireNonNull(player.getMyPlaylist()).get(position));
        audioAdapter.notifyItemRemoved(position);

        ((SimpleItemAnimator) recyclerView.getItemAnimator()).setSupportsChangeAnimations(false);
    }

    @Override
    public void onStopped(@NotNull JcStatus status) {

    }

    /**
     * Called when leaving the activity
     */
    @Override
    public void onPause() {
        if (mAdView != null) {
            mAdView.pause();
        }
        super.onPause();
    }

    /**
     * Called when returning to the activity
     */
    @Override
    public void onResume() {
        super.onResume();
        if (mAdView != null) {
            mAdView.resume();
        }
    }

    /**
     * Called before the activity is destroyed
     */
    @Override
    public void onDestroy() {
        if (mAdView != null) {
            mAdView.destroy();
        }
        super.onDestroy();
    }

    }
