### ISSUE TITLE
How to programmatically change the starting position of audio? 

### ISSUE THREAD

**Issue by alierdogan7** [jeancsanchez/JCPlayer#70]
I tried setting a new starting point for a specific audio (I don't want the first few seconds to be played) 

`jcStatus.setCurrentPosition(newStartPointInMs)` in onPreparedAudio event listener of JcPlayerManager singleton object's listener. 

It doesn't affect at all. I'm seeking a kind of seekTo() function in this library. How to do this programmatically? 

Regards.

**Comment by jeancsanchez** [comment]
Get an instance of  `JcPlayerManager.getInstance(...)` and call method  `seekTo(..)`
