### ISSUE TITLE
Pause the player after completion

### ISSUE THREAD

**Issue by fumatamax** [jeancsanchez/JCPlayer#72]
I'm trying to pause the audio player once playback is complete. But I can't find any solution and I can't find the documentation that tells you how to pause once the audio is complete.

This is what I'm doing, but it gives me failure:

```
@Override
    public void onCompletedAudio() {
         player.pause();
    }
```
**How can I fix this?**

**Comment by jeancsanchez** [comment]
Did you set your activity as listener `player.setJcPlayerManagerListener(this)`?

**Comment by fumatamax** [comment]
I haven't added `player.setJcPlayerManagerListener(this)`
could you give me an example of how once the audio has been completely heard, pause and don't jump to the next track

**Comment by fumatamax** [comment]
jeancsanchez could you give me an example to be able to apply the pause once the audio track is complete, thanks.

**Comment by fumatamax** [comment]
> Did you set your activity as listener `player.setJcPlayerManagerListener(this)`?

Excuse me, but could you give me a few examples. How to use `player.setJcPlayerManagerListener(this)`

**Comment by peace-shillong** [comment]
@fumatamax I know @jeancsanchez is busy...
P.S : "@jeancsanchez if you can read this please check my email, and can you kindly get back to me..."

You can use player.setJcPlayerManagerListener(this) or let your Class implement JcPlayerManagerListener
and override all the methods of the interface
And to Stop the Player you simply need these lines below
(You already have this method, so when your Class implement the JcPlayerManagerLister interface or set player.setJcPlayerManagerListener(this) in your onCreate method it should work )

  @Override
    public void onCompletedAudio() {
        player.pause();
    }
-----------------

Just an update : i've tested the above code and it did not worked for me, so I added the player.pause in the onStopped() :a method implemented from the JcPlayerManagerListener interface and it should worked, but still i did not see any change...hope it works for you

  @Override
    public void onStopped(JcStatus status) {
        player.pause();
    }

**Comment by fumatamax** [comment]
Thank you very much @peace-shillong , excuse me for being so insistent. Tell you that I love your contribution to the community and that you continue with the project ahead.

I also wanted to ask you if you have the option to share the Player, I mean. Just as has the button to delete the Player, which has another button or the option to share.
