### ISSUE TITLE
Cannot resolve symbol 'jetbrains'

### ISSUE THREAD

**Issue by VikasGutte** [jeancsanchez/JCPlayer#89]
Cannot resolve symbol 'jetbrains'

Tried **Rebuild**, **Invalidate Cache/ Restart** and so on nothing is working...!

![image](https://user-images.githubusercontent.com/30354348/56439753-e7b61680-6304-11e9-8bf1-3fb97e0afa51.png)

![image](https://user-images.githubusercontent.com/30354348/56439765-f43a6f00-6304-11e9-96cb-74295cf01d80.png)

![image](https://user-images.githubusercontent.com/30354348/56439911-5dba7d80-6305-11e9-8dce-4127527abb19.png)

**Comment by jeancsanchez** [comment]
This is not an issue related to the library, so I am closing it. Thank you.
