### ISSUE TITLE
ReceiverCallNotAllowedException

### ISSUE THREAD

**Issue by melihakalan** [jeancsanchez/JCPlayer#90]
![jcerror](https://user-images.githubusercontent.com/6933323/56848687-78d45100-68f4-11e9-9ea9-285c89e4ff56.JPG)

May be related to : https://stackoverflow.com/a/34752888/3147496

In your code, I see you use:
this.context.bindService(intent, (ServiceConnection)this, 1);

**Comment by rajjani88** [comment]
when i close application and reopen seekbar and title not showing already playing song
