### ISSUE TITLE
how to play google drive mp3 file 

### ISSUE THREAD

**Issue by MustafaAndroid** [jeancsanchez/JCPlayer#91]
I'm using this library to play audio but the problem is the client is uploading google drive link and its not playing so it is possible to play.?

**Comment by jeancsanchez** [comment]
Yes. But the link must be public to work properly I think.

**Comment by MustafaAndroid** [comment]
the link is proper and back-end team send properly but the problem is the end time is not showing and forward is also not working.What will be the solution.??

**Comment by MustafaAndroid** [comment]
this is the link of  that play audio without end time

https://docs.google.com/uc?export=download&id=1UZDHvWjLki4NKUyPqRGwcArGbTM86lKa

**Comment by peace-shillong** [comment]
> this is the link of that play audio without end time
> 
> https://docs.google.com/uc?export=download&id=1UZDHvWjLki4NKUyPqRGwcArGbTM86lKa

Hey There, this is a good Question, even I'm still wondering why this happens.
The url is public and I'm getting the same problem while playing.

@MustafaAndroid  Why not try to upload the file on a different server and see, let us know what you find.
Thanks

**Comment by peace-shillong** [comment]
@MustafaAndroid @jeancsanchez 
Hey guys I took the file that did prevented the seekbar from moving and imported to Audacity.  
Then I downloaded lame mp3 dll to help me export the file to mp3.
So I exported the mp3 with default values and added some meta data when asked( Title,  artist,) and then uploaded the exported file. 
And now I played the song and I can move the seekbar.

Hey @MustafaAndroid can you try it out also and see if it works.

Could be because of the codecs....

**Comment by MustafaAndroid** [comment]
@peace-shillong  can you show the snippet how you play it dynamically..???

**Comment by peace-shillong** [comment]
@MustafaAndroid I'm using the default source code to play songs.

Are you using Kotlin or the Java code?

**Comment by peace-shillong** [comment]
For code snippet on how to play the audio from url 
Check out the MainActivity from the project file

https://github.com/jeancsanchez/JcPlayer/tree/master_v2/sample/src/main/java/com/example/jean/jcplayersample

Can you be more specific on playing it dynamically?

**Comment by MustafaAndroid** [comment]
java and i want to know that how you convert into lame..??

**Comment by peace-shillong** [comment]
For java check the MainActivity from here
https://github.com/jeancsanchez/JcPlayer/tree/master_v1/sample/src/main/java/com
Line no 35 check out the commented line


Ok. I will send you the process to export the file as mp3 ( using lame.dll) in audacity

**Comment by peace-shillong** [comment]
![a1](https://user-images.githubusercontent.com/33800152/60681477-fac09780-9eac-11e9-8691-8a1b34400081.JPG)
1. First Install audacity (a1)

![a2](https://user-images.githubusercontent.com/33800152/60681499-1fb50a80-9ead-11e9-9a3c-e8fddd704d75.JPG)
2. DOWNLOAD THE DLL FILE FROM HERE (32/64 bit)
http://www.dlldownloader.com/lame_enc-dll/

![a3](https://user-images.githubusercontent.com/33800152/60681522-38bdbb80-9ead-11e9-9f2c-541981e224c7.jpg)

3. Open  Audacity and lets change the Preferences

![a4](https://user-images.githubusercontent.com/33800152/60681539-47a46e00-9ead-11e9-9b17-8abbfb642f61.jpg)

4. Click on Libraries and click Locate , you will now need to browse and select the dll file which you downloaded (make sure you extract the zip file). Once you have selected the dll click ok
![s6](https://user-images.githubusercontent.com/33800152/60681649-b7b2f400-9ead-11e9-8783-2b49a7b88b2c.jpg)

5. Open your file in Audacity and Click File->Export Audio. 
You will then have to enter the file name and you can enter the meta data as seen in the picture and click OK.

Your file will be export to mp3 using audacity.

Note: I've skip plenty of steps in between, but they are very easy to do. I hope this is good enough to get you started.

**Comment by MustafaAndroid** [comment]
@peace-shillong  thanks bro but I'm little bit confusing about lame that if we convert into Audacity but the file is from backend which I'm playing in jcplayer so how it is possible ..??

**Comment by peace-shillong** [comment]
After you have exported the file, you will need to upload the exported file to drive just like what you did previously and then use the download url to play the file.

This is getting a bit long, you can just send me an email and I will help you out.

**Comment by peace-shillong** [comment]
jcAudios.add(JcAudio.createFromURL("url audio","https://docs.google.com/uc?export=download&id=1UZDHvWjLki4NKUyPqRGwcArGbTM86lKa"));

This is the line 35 from MainAcitivity in Java.
Use this to add the file to the list, and it will be playable

**Comment by peace-shillong** [comment]
@jeancsanchez @MustafaAndroid I've found the reason for all this.
Please check the image, I exported the audio with those options and my audio plays nicely without any problem when seeking: @jeancsanchez if you don't understand let me know.
![audacity working](https://user-images.githubusercontent.com/33800152/64371116-6ce46280-d03d-11e9-8c68-5f5d0ce38a7c.JPG)
![Uploading audacity working.JPG…]()


@jeancsanchez We need to look into the player nicely as to why other sample rates are not supported. 

@MustafaAndroid If you want to play the song in the player please get The Share+ (Sharable Link) and get the direct download link of the file. Then use the direct download link as the link to the file for playing. follow this site to get the direct download link https://sites.google.com/site/gdocs2direct/

@MustafaAndroid @jeancsanchez this should fix and closes #91 

Summary:  What I found
1. Songs with the above Specifications[see image] (Export Settings) plays smoothly in the player.
2. How to play songs from Google Drive: 
Steps on how to play song from google drive
2.a Upload Song to Drive
2.b Get the Share+ Link of the file 
2.c goto  https://sites.google.com/site/gdocs2direct/ and get the direct download link
2.d use the direct download link as the link to play the file from.

SIDE NOTE: 
@MustafaAndroid 
jcAudios.add(JcAudio.createFromURL("url audio","https://docs.google.com/uc?export=download&id=xxxxxxxx"));
Please replace xxxxxx with the id of the new uploaded file
This should work, all you need is to export the file with the above options.

AND yes you need not worry about LAME anymore. 
If you have installed audacity please remove it and download the latest version, LAME is now in build with Audacity and you don't need any other extra setup.
(What does this means: It means with the new version you can simply install audacity, then open the file and export it to mp3 with the above settings and you can then upload the new file to google drive and play it in the app)

**Comment by jeancsanchez** [comment]
@peace-shillong Thank you so much for this. I think this issue can be closed. What we need now is to discover why [MediaPlayer](https://developer.android.com/guide/topics/media/mediaplayer) class (because JcPlayer uses it to play the songs) doesn't support other rates.
