### ISSUE TITLE
 I'm gettin null pointer  on JcPlayerView 

### ISSUE THREAD

**Issue by utkuberaty** [jeancsanchez/JCPlayer#93]
Hi, I'm trying to use your library but when I set the JcPlayerView with findById my getting null pointer. I check the package name but it's also correct.

`  <com.example.jean.jcplayer.view.JcPlayerView
        android:id="@+id/jcplayer"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"/>`

`        player = findViewById(R.id.jcplayer);
`

**Comment by eliazar1813** [comment]
I have the same problem were you able to fix it ? If yes can you tell me
How please

**Comment by jeancsanchez** [comment]
Can you paste all code here?

**Comment by jeancsanchez** [comment]
I'm closing this issue due to lack of more context and supplies.
