### ISSUE TITLE
Support for ExoPlayer

### ISSUE THREAD

**Issue by prokash-sarkar** [jeancsanchez/JCPlayer#94]
Can we replace the existing **MediaPlayer** with **ExoPlayer**?

**Comment by jeancsanchez** [comment]
@prokash-sarkar It's a good idea, but we need to refactor the code to support that in a lightweight way.

**Comment by peace-shillong** [comment]
@jeancsanchez @prokash-sarkar support for ExoPlayer would be good. If you guys plan or think of doing it let us know but it's best you create a new repository all together, a separate one since it would require a lot of changes.
